version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins
    build:
      context: jenkins
    ports:
      - "8080:8080"
    volumes:
      - "$PWD/jenkins_home:/var/jenkins_home"
    networks:
      - net
networks:
  net: